# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
---
blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/xudyang1/redir.nvim/discussions
    about: Please ask and answer questions here.
