name: Feature Request
description: Suggest a new feature
title: "feature: "
labels: ["enhancement", "triage"]
assignees:
  - xudyang1
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for wanting to suggest a feature for redir.nvim!**
  - type: checkboxes
    attributes:
      label: Did you check the docs?
      description: Make sure you read the README.md before submitting a feature request
      options:
        - label: I have read the redir.nvim README.md
          required: true
  - type: textarea
    id: describe-the-feature
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      value: "E.g: I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: describe-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
