---
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  formatting:
    uses: ./.github/workflows/formatting.yaml

  linting:
    uses: ./.github/workflows/linting.yaml

  unit_test:
    uses: ./.github/workflows/unit_tests.yaml
