---
on:
  push:
    branches:
      - main
name: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v4

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: redir.nvim
          version: "NVIM v0.8.0"
          demojify: true
          treesitter: true

      - name: push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(build): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
