name: Linting and style checking

on: [push, pull_request]

jobs:
  Linting:
    name: Luacheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Luacheck linting
        run: sudo luacheck lua/redir tests

  Formatting:
    name: stylua
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.20.0
          # CLI arguments
          args: --color always --check lua/ tests/
