---
name: Linting

on: workflow_call

jobs:
  linting:
    name: luacheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: prepare luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: luacheck linting
        run: sudo luacheck lua/redir tests
